import { Inter } from "next/font/google"
import Head from "next/head"

import AddToDo from "@/components/AddToDo"
import Todos from "@/components/Todos"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>TRPC - Basics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>TRPC Basics</h1>
        <AddToDo />
        <br />
        <hr />
        <hr />
        <Todos />
      </main>
    </>
  )
}
